[project]
name = "my_attention"
version = "0.1.0"
description = "Mixture-of-Experts FFN (top-k routing, capacity, renorm/drop) with dense/SwiGLU experts."
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["torch"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["my_attention*"]